name: Build and deploy to production
on: 
  push:
    branches: 
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash 
    - name: Install dependencies
      run: |
        bun install
    - name: Run the bot
      run: |
        bun run
    - name: rsync files
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --delete
        path: /
        remote_path: /home/fribyte/friBot
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.KEY }}